name: Deploy linebot
on:
  push:
    branches:
      - main
jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: copy to remote
        run: rsync -avhzr ./linebot/* ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}}:/root/linebot && rsync -avhzr ./server/* ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}}:/root/server
